In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Initialising the Class ---------------->

# class GaussianNaiveBayes:
#     def fit(self, X, y):
#         self.classes = np.unique(y)
#         self.means = {}
#         self.variances = {}
#         self.priors = {}

#         for cls in self.classes:
#             X_cls = X[y == cls]
#             self.means[cls] = X_cls.mean(axis=0)
#             self.variances[cls] = X_cls.var(axis=0)
#             self.priors[cls] = len(X_cls) / len(X)

#     def _calculate_likelihood(self, X, cls):
#         mean = self.means[cls]
#         var = self.variances[cls]
#         likelihood = np.exp(- (X - mean) ** 2 / (2 * var)) / np.sqrt(2 * np.pi * var)
#         return np.prod(likelihood, axis=1)

#     def predict(self, X):
#         predictions = []
#         for _, row in X.iterrows():
#             posteriors = []
#             for cls in self.classes:
#                 prior = np.log(self.priors[cls])
#                 likelihood = np.log(self._calculate_likelihood(pd.DataFrame([row], columns=X.columns), cls))
#                 posterior = prior + np.sum(likelihood)
#                 posteriors.append(posterior)
#             predictions.append(self.classes[np.argmax(posteriors)])
#         return np.array(predictions)

In [3]:
#Dataset ---------->

data = pd.read_csv('01_District_wise_crimes_committed_IPC_2001_2012.csv')
data

,STATE/UT,YEAR,MURDER,ATTEMPT TO MURDER,RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,RIOTS,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,CRUELTY BY HUSBAND OR HIS RELATIVES
0,ANDHRA PRADESH,2001,101,60,50,46,9,0,41,198,199,78,104,1,30,1131,16,175
1,ANDHRA PRADESH,2001,151,125,23,53,8,0,16,191,366,168,65,8,69,1543,7,154
2,ANDHRA PRADESH,2001,101,57,27,59,4,0,14,237,723,156,209,9,38,2088,14,186
3,ANDHRA PRADESH,2001,80,53,20,25,1,0,4,98,173,164,37,2,23,795,17,57
4,ANDHRA PRADESH,2001,82,67,23,49,4,0,25,437,1021,70,220,3,41,1244,12,247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9012,LAKSHADWEEP,2012,0,0,0,0,0,0,0,3,7,10,0,0,3,3,0,1
9013,LAKSHADWEEP,2012,0,0,0,0,0,0,0,3,7,10,0,0,3,3,0,1
9014,PUDUCHERRY,2012,5,6,6,2,0,1,3,21,81,17,15,1,1,186,0,1
9015,PUDUCHERRY,2012,24,21,7,17,5,14,13,56,577,109,75,5,20,632,0,5
9016,PUDUCHERRY,2012,29,27,13,19,5,15,16,77,658,126,90,6,21,818,0,6

In [5]:
# Calculating Total Violent Crimes ------------->

data['Total Violent Crimes'] = 0
data['Total Violent Crimes'] = data.iloc[:,2:].sum(axis=1)
data

,STATE/UT,YEAR,MURDER,ATTEMPT TO MURDER,RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,THEFT,RIOTS,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,CRUELTY BY HUSBAND OR HIS RELATIVES,Total Violent Crimes
0,ANDHRA PRADESH,2001,101,60,50,46,9,0,41,198,199,78,104,1,30,1131,16,175,2239
1,ANDHRA PRADESH,2001,151,125,23,53,8,0,16,191,366,168,65,8,69,1543,7,154,2947
2,ANDHRA PRADESH,2001,101,57,27,59,4,0,14,237,723,156,209,9,38,2088,14,186,3922
3,ANDHRA PRADESH,2001,80,53,20,25,1,0,4,98,173,164,37,2,23,795,17,57,1549
4,ANDHRA PRADESH,2001,82,67,23,49,4,0,25,437,1021,70,220,3,41,1244,12,247,3545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9012,LAKSHADWEEP,2012,0,0,0,0,0,0,0,3,7,10,0,0,3,3,0,1,27
9013,LAKSHADWEEP,2012,0,0,0,0,0,0,0,3,7,10,0,0,3,3,0,1,27
9014,PUDUCHERRY,2012,5,6,6,2,0,1,3,21,81,17,15,1,1,186,0,1,346
9015,PUDUCHERRY,2012,24,21,7,17,5,14,13,56,577,109,75,5,20,632,0,5,1580
9016,PUDUCHERRY,2012,29,27,13,19,5,15,16,77,658,126,90,6,21,818,0,6,1926

In [7]:
# Convert categorical '# Convert categorical 'STATE/UT' column to one-hot encoding
df = pd.get_dummies(data, columns=['STATE/UT'])


# Create a target variable -------->

df['Crime_Label'] = pd.cut(df['Total Violent Crimes'], bins=3, labels=['Low', 'Medium', 'High'])
df = df.drop(columns=['Total Violent Crimes'])

In [9]:
# Prepare features and labels ----------->

X = df.drop(columns=['Crime_Label'])
y = df['Crime_Label']

X,y

(      YEAR  MURDER  ATTEMPT TO MURDER  RAPE  KIDNAPPING & ABDUCTION  DACOITY  \
 0     2001     101                 60    50                      46        9
 1     2001     151                125    23                      53        8
 2     2001     101                 57    27                      59        4
 3     2001      80                 53    20                      25        1
 4     2001      82                 67    23                      49        4
 ...    ...     ...                ...   ...                     ...      ...
 9012  2012       0                  0     0                       0        0
 9013  2012       0                  0     0                       0        0
 9014  2012       5                  6     6                       2        0
 9015  2012      24                 21     7                      17        5
 9016  2012      29                 27    13                      19        5

       PREPARATION AND ASSEMBLY FOR DACOITY  ROBBERY  BURGLARY  THEFT  ...  \
 0                                        0       41       198    199  ...
 1                                        0       16       191    366  ...
 2                                        0       14       237    723  ...
 3                                        0        4        98    173  ...
 4                                        0       25       437   1021  ...
 ...                                    ...      ...       ...    ...  ...
 9012                                     0        0         3      7  ...
 9013                                     0        0         3      7  ...
 9014                                     1        3        21     81  ...
 9015                                    14       13        56    577  ...
 9016                                    15       16        77    658  ...

       STATE/UT_ODISHA  STATE/UT_PUDUCHERRY  STATE/UT_PUNJAB  \
 0               False                False            False
 1               False                False            False
 2               False                False            False
 3               False                False            False
 4               False                False            False
 ...               ...                  ...              ...
 9012            False                False            False
 9013            False                False            False
 9014            False                 True            False
 9015            False                 True            False
 9016            False                 True            False

       STATE/UT_RAJASTHAN  STATE/UT_SIKKIM  STATE/UT_TAMIL NADU  \
 0                  False            False                False
 1                  False            False                False
 2                  False            False                False
 3                  False            False                False
 4                  False            False                False
 ...                  ...              ...                  ...
 9012               False            False                False
 9013               False            False                False
 9014               False            False                False
 9015               False            False                False
 9016               False            False                False

       STATE/UT_TRIPURA  STATE/UT_UTTAR PRADESH  STATE/UT_UTTARAKHAND  \
 0                False                   False                 False
 1                False                   False                 False
 2                False                   False                 False
 3                False                   False                 False
 4                False                   False                 False
 ...                ...                     ...                   ...
 9012             False                   False                 False
 9013             False                   False                 False
 9014             False                   False                 False
 9015             False                   False                 False
 9016             False                   False                 False

       STATE/UT_WEST BENGAL
 0                    False
 1                    False
 2                    False
 3                    False
 4                    False
 ...                    ...
 9012                 False
 9013                 False
 9014                 False
 9015                 False
 9016                 False

 [9017 rows x 52 columns],
 0       Low
 1       Low
 2       Low
 3       Low
 4       Low
        ...
 9012    Low
 9013    Low
 9014    Low
 9015    Low
 9016    Low
 Name: Crime_Label, Length: 9017, dtype: category
 Categories (3, object): ['Low' < 'Medium' < 'High'])

In [11]:
# Split the data ------------------->

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# train the GaussianNaiveBayes ------------->

# gnb = GaussianNaiveBayes()
# gnb.fit(X_train, y_train)

# # Make predictions -------------->
# y_pred = gnb.predict(X_test)

# # Print predictions and evaluate -------------------->
# print("Predictions:", y_pred)
# print("Accuracy Score:", accuracy_score(y_test, y_pred))


# Fitting Gaussian Naive Bayes model------------>
classes = np.unique(y_train)
means = {}
variances = {}
priors = {}

for cls in classes:
    X_cls = X_train[y_train == cls]
    means[cls] = X_cls.mean(axis=0)
    variances[cls] = X_cls.var(axis=0)
    priors[cls] = len(X_cls) / len(X_train)

def calculate_likelihood(X, cls, means, variances):
    mean = means[cls]
    var = variances[cls]
    likelihood = np.exp(- (X - mean) ** 2 / (2 * var)) / np.sqrt(2 * np.pi * var)
    return np.prod(likelihood, axis=1)

def predict(X, classes, means, variances, priors):
    predictions = []
    for _, row in X.iterrows():
        posteriors = []
        for cls in classes:
            prior = np.log(priors[cls])
            likelihood = np.log(calculate_likelihood(pd.DataFrame([row], columns=X.columns), cls, means, variances))
            posterior = prior + np.sum(likelihood)
            posteriors.append(posterior)
        predictions.append(classes[np.argmax(posteriors)])
    return np.array(predictions)

# Making predictions ------------>
y_pred = predict(X_test, classes, means, variances, priors)

# Print prediction and evaluate --------------->>
print("Predictions:", y_pred)
print("Accuracy Score:", accuracy_score(y_test, y_pred))  # Evaluating the model

C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\dipay\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

Predictions: ['Medium' 'Low' 'Low' ... 'Low' 'Low' 'Low']
Accuracy Score: 0.9571322985957132